/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProcessOutput {
  status: number
  stdout: string
  stderr: string
}
export interface PgResponse {
  code: string
  message: string
}
export declare function runNpmScript(script: string): Promise<ProcessOutput>
export declare function testPostgresUrl(url: string): Promise<PgResponse>
export declare function createDatabase(url: string, database: string): Promise<PgResponse>
export declare function testRedisParameters(host: string, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export declare function fileExists(filePath: string): boolean
